CREATE DATABASE cadastro;
USE cadastrope;
 
CREATE TABLE tbcadastrope (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    email VARCHAR(200) NOT NULL,
    senha VARCHAR(200) NOT NULL
);
 

